import Head from "next/head";
import Sidebar from "../components/Sidebar";
import { useAuthState, UseAuthState } from "react-firebase-hooks/auth";
import { auth } from "../firebase";
import firebase from "firebase";

export default function Home() {
  const [user] = useAuthState(auth);
  return (
    <div>
      <Head>
        <title>Welcome | {user.displayName}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar />
    </div>
  );
}
