// Modules Import
import Head from "next/head";
import { useAuthState } from "react-firebase-hooks/auth";

// File Import
import { auth } from "../Config/FirebaseConfig";
import Sidebar from "../components/Sidebar";

/**
 *
 * @returns Webpage Head and It's Details.
 */
export default function Home() {
  const [user] = useAuthState(auth);
  return (
    <div>
      <Head>
        <title>Welcome | {user.displayName}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar />
    </div>
  );
}
